language: node_js
node_js:
  - lts/*
before_script:
  - npm install @11ty/eleventy -g
  - npm install markdown-it markdown-it-anchor
script:
  - eleventy
  - echo -n nationalunionofthehomeless.org > _site/CNAME
deploy:
  local-dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: main
